CREATE DATABASE CrudJava;
USE CrudJava;
CREATE TABLE Productos(id INT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(50)NOT NULL, precio DOUBLE NOT NULL, cantidad INT NOT NULL, PRIMARY KEY(id));
CREATE TABLE Usuarios(id INT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(50)NOT NULL, apellido VARCHAR(50) NOT NULL, edad INT NOT NULL, genero VARCHAR(50) NOT NULL, correo VARCHAR(50)NOT NULL, PRIMARY KEY(id));